// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { CaseClassification } from "./CaseClassification";
import type { CaseId } from "./CaseId";
import type { CaseStatus } from "./CaseStatus";
import type { TagId } from "./TagId";

/**
 * Ein Fall.
 */
export type Case = { 
/**
 * Technische ID (UUIDv7).
 */
id: CaseId, 
/**
 * Menschlich lesbare Fallnummer, z. B. `DFIR-2026-0017`.
 */
case_number: string, 
/**
 * Titel.
 */
title: string, 
/**
 * Beschreibung.
 */
description: string | null, 
/**
 * Stand.
 */
status: CaseStatus, 
/**
 * Einstufung.
 */
classification: CaseClassification, 
/**
 * Angelegt am.
 */
created_at: string, 
/**
 * Angelegt von.
 */
created_by: ActorId, 
/**
 * Eröffnet am.
 */
opened_at: string | null, 
/**
 * Geschlossen am.
 */
closed_at: string | null, 
/**
 * Zeitzone für die Anzeige (Analysezeiten bleiben UTC).
 */
timezone: string | null, 
/**
 * Fallordner auf dem Server, in dem die Evidence-Dateien liegen.
 */
case_folder: string | null, 
/**
 * Schlagworte.
 */
tags: Array<TagId>, };
