// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bearbeitungsstand eines Falls.
 */
export type CaseStatus = "new" | "active" | "review" | "suspended" | "closed" | "archived";
