// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Einstufung eines Falls. Die Stufen sind ein Vorschlag; die Zielarchitektur
 * legt sie nicht fest (Grundlage für spätere attributbasierte Rechte).
 */
export type CaseClassification = "open" | "internal" | "confidential" | "strictly_confidential";
