// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wie ein Objekt entstanden ist. Beobachtetes und Gefolgertes werden nie
 * gleich behandelt; die Oberfläche zeigt diesen Status immer an.
 */
export type DerivationKind = "observed" | "parsed" | "derived" | "correlated" | "reconstructed" | "simulated" | "analyst_asserted" | "external_intel" | "ai_suggested";
