// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Art einer Entität.
 */
export type EntityKind = "host" | "user_account" | "user_group" | "file" | "file_stream" | "directory" | "volume" | "network_share" | "process" | "service" | "scheduled_task" | "registry_key" | "registry_value" | "ip_address" | "network_endpoint" | "domain_name" | "url" | "mac_address" | "network_interface" | "email_address" | "browser_profile" | "usb_device" | "certificate" | "credential" | "hash" | "software" | "package" | "container" | "virtual_machine" | "database" | "database_account" | "cloud_account" | "cloud_resource" | "mobile_device" | "application" | "malware" | "tool" | "other";
