// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { CaseId } from "./CaseId";
import type { EvidenceId } from "./EvidenceId";
import type { EvidenceKind } from "./EvidenceKind";
import type { EvidenceSupport } from "./EvidenceSupport";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Ein Beweisobjekt in einem Fall.
 */
export type Evidence = { 
/**
 * Technische ID des Imports (UUIDv7).
 */
id: EvidenceId, 
/**
 * Fall.
 */
case_id: CaseId, 
/**
 * Art.
 */
kind: EvidenceKind, 
/**
 * Anzeigename.
 */
name: string, 
/**
 * System oder Rolle, zu der die Evidence gehört (z. B. „Webserver“).
 */
role: string | null, 
/**
 * Ursprünglicher Dateiname.
 */
original_name: string | null, 
/**
 * Ablageort (Pfad oder URI).
 */
source_uri: string, 
/**
 * Größe in Byte (bei E01 die Mediengröße).
 */
size: number, 
/**
 * SHA-256 über die Mediendaten (hex).
 */
sha256: string, 
/**
 * BLAKE3 über die Mediendaten (hex).
 */
blake3: string, 
/**
 * Zeitpunkt der Sicherung, falls bekannt (z. B. aus dem E01-Kopf).
 */
acquired_at: string | null, 
/**
 * Zeitpunkt des Imports in stratum.
 */
imported_at: string, 
/**
 * Importiert von.
 */
imported_by: ActorId, 
/**
 * Sicherungsverfahren bzw. -werkzeug.
 */
acquisition_method: string | null, 
/**
 * Nur lesend eingebunden (immer `true` bei stratum).
 */
read_only: boolean, 
/**
 * Stand der Auswertbarkeit.
 */
support: EvidenceSupport, 
/**
 * Übergeordnete Evidence (z. B. bei extrahierten Dateien).
 */
parent_evidence_id: EvidenceId | null, 
/**
 * Weitere Angaben (z. B. Akquisedaten und Akquise-Hashes eines E01).
 */
metadata: JsonValue, };
