// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evidence-Import (ein Beweisobjekt in einem Fall).
 */
export type EvidenceId = string;
