// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Art eines Beweisobjekts.
 */
export type EvidenceKind = "raw_disk_image" | "e01_image" | "vhd_image" | "directory" | "file_collection" | "pcap" | "network_flow" | "log_bundle" | "mobile_backup" | "android_image" | "ios_backup" | "memory_dump" | "registry_hive" | "database" | "cloud_export" | "other";
