// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wie weit stratum ein Beweisobjekt auswerten kann. Erkennung, erfolgreiche
 * Auswertung und fehlende Schlüssel werden getrennt ausgewiesen; nicht
 * unterstützte Arten werden trotzdem registriert und gehasht.
 */
export type EvidenceSupport = "recognized" | "analyzed" | "unsupported_format" | "key_missing";
