// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { AnalysisRunId } from "./AnalysisRunId";
import type { CaseId } from "./CaseId";
import type { JobId } from "./JobId";
import type { JobKind } from "./JobKind";
import type { JobStatus } from "./JobStatus";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Ein Job.
 */
export type Job = { 
/**
 * ID (UUIDv7).
 */
id: JobId, 
/**
 * Fall.
 */
case_id: CaseId, 
/**
 * Art.
 */
kind: JobKind, 
/**
 * Stand.
 */
status: JobStatus, 
/**
 * Parameter (bei Analysen: Evidence und Optionen, nie Geheimnisse).
 */
parameters: JsonValue, 
/**
 * Letzter Fortschritt (Phase, erledigt, gesamt, Meldung).
 */
progress: JsonValue, 
/**
 * Angelegt von; der Job läuft in seinem Namen.
 */
created_by: ActorId, 
/**
 * Angelegt am.
 */
created_at: string, 
/**
 * Begonnen am.
 */
started_at: string | null, 
/**
 * Beendet am.
 */
finished_at: string | null, 
/**
 * Worker, der ihn ausführt bzw. ausgeführt hat.
 */
worker: string | null, 
/**
 * Abbruch angefordert.
 */
cancel_requested: boolean, 
/**
 * Fehlermeldung.
 */
error: string | null, 
/**
 * Zugehöriger Analyselauf.
 */
analysis_run_id: AnalysisRunId | null, 
/**
 * Ergebnis (z. B. Report-Pfad und SHA-256).
 */
result: JsonValue | null, };
