// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stand eines Jobs.
 */
export type JobStatus = "queued" | "running" | "completed" | "failed" | "cancelled";
