// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisRunId } from "./AnalysisRunId";
import type { ArtifactId } from "./ArtifactId";
import type { CaseId } from "./CaseId";
import type { EntityId } from "./EntityId";
import type { EventId } from "./EventId";
import type { EvidenceId } from "./EvidenceId";
import type { FindingId } from "./FindingId";
import type { ObservationId } from "./ObservationId";
import type { RelationshipId } from "./RelationshipId";

/**
 * Verweis auf ein Objekt des Modells.
 */
export type ObjectRef = { "type": "case", "id": CaseId } | { "type": "evidence", "id": EvidenceId } | { "type": "analysis_run", "id": AnalysisRunId } | { "type": "artifact", "id": ArtifactId } | { "type": "observation", "id": ObservationId } | { "type": "entity", "id": EntityId } | { "type": "event", "id": EventId } | { "type": "relationship", "id": RelationshipId } | { "type": "finding", "id": FindingId };
