// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direkt extrahierter Sachverhalt (abgeleitet).
 */
export type ObservationId = string;
