// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eine einzelne Berechtigung.
 */
export type Permission = "case.create" | "case.view" | "case.edit" | "case.close" | "evidence.import" | "evidence.view" | "analysis.start" | "analysis.cancel" | "file.view" | "file.extract" | "search.run" | "credential.view_sensitive" | "bookmark.edit" | "finding.create" | "finding.edit" | "relation.edit" | "report.create" | "report.export" | "audit.view" | "audit.verify" | "ti.manage" | "playbook.run" | "ai.query" | "connector.use";
