// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rolle (frei angelegtes Bündel von Berechtigungen).
 */
export type RoleId = string;
