// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { RoleId } from "./RoleId";

/**
 * Eine Rolle: frei benanntes Bündel von Berechtigungen.
 */
export type Role = { 
/**
 * ID.
 */
id: RoleId, 
/**
 * Eindeutiger Name.
 */
name: string, 
/**
 * Beschreibung.
 */
description: string | null, 
/**
 * Berechtigungen.
 */
permissions: Array<Permission>, };
