// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stand eines Kontos.
 */
export type UserStatus = "pending" | "active" | "disabled" | "rejected";
