// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { RoleId } from "./RoleId";
import type { UserKind } from "./UserKind";
import type { UserStatus } from "./UserStatus";

/**
 * Ein Benutzerkonto.
 */
export type User = { 
/**
 * ID; dieselbe wie in `created_by`, `imported_by` und im Audit.
 */
id: ActorId, 
/**
 * Anmeldename (klein, `a-z 0-9 . _ -`).
 */
username: string, 
/**
 * Anzeigename.
 */
display_name: string, 
/**
 * Art.
 */
kind: UserKind, 
/**
 * Stand.
 */
status: UserStatus, 
/**
 * Superadmin: verwaltet Konten und Rollen, hat alle Rechte.
 */
superadmin: boolean, 
/**
 * Angelegt bzw. registriert am.
 */
created_at: string, 
/**
 * Rollen.
 */
roles: Array<RoleId>, 
/**
 * Muss zuerst ein eigenes Passwort setzen (Startpasswort oder vom
 * Superadmin zurückgesetzt); bis dahin ist nichts anderes erlaubt.
 */
password_change_required: boolean, };
