// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Art eines Eintrags.
 */
export type WarRoomEntryKind = "analyst_message" | "analyst_note" | "search" | "query_result" | "entity_opened" | "artifact_opened" | "finding_created" | "finding_updated" | "playbook_started" | "playbook_step" | "playbook_completed" | "reconstruction_started" | "replay_request" | "replay_result" | "threat_intel_match" | "connector_result" | "ai_question" | "ai_answer" | "file_extracted" | "report_generated" | "system_event";
