// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorId } from "./ActorId";
import type { AuditEventId } from "./AuditEventId";
import type { CaseId } from "./CaseId";
import type { ObjectRef } from "./ObjectRef";
import type { WarRoomEntryId } from "./WarRoomEntryId";
import type { WarRoomEntryKind } from "./WarRoomEntryKind";

/**
 * Ein Eintrag im War Room.
 */
export type WarRoomEntry = { 
/**
 * ID (UUIDv7).
 */
id: WarRoomEntryId, 
/**
 * Fall.
 */
case_id: CaseId, 
/**
 * Zeitpunkt (Untersuchungszeit).
 */
timestamp: string, 
/**
 * Wer: Analyst, oder bei Systemereignissen der Auftraggeber des Jobs.
 */
actor: ActorId, 
/**
 * Art.
 */
kind: WarRoomEntryKind, 
/**
 * Verknüpfte Objekte des Modells.
 */
object_refs: Array<ObjectRef>, 
/**
 * Inhalt (Text, Kennzahlen, Job-ID …).
 */
payload: Record<string, unknown>, 
/**
 * Eintrag, auf den sich dieser bezieht.
 */
parent_entry_id: WarRoomEntryId | null, 
/**
 * Audit-Ereignis der Handlung; bei Einträgen des Workers leer, sie
 * verweisen über `payload.job_id` auf den Job.
 */
audit_event_id: AuditEventId | null, };
