[package]
name = "stratum-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "ip"
path = "fuzz_targets/ip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "usb"
path = "fuzz_targets/usb.rs"
test = false
doc = false
bench = false

[dependencies]
stratum-connectors = { path = "../connectors" }
libfuzzer-sys = "0.4.13"
stratum-core = { path = "../core" }
stratum-registry = { path = "../registry" }
stratum-ese = { path = "../ese" }
stratum-vss = { path = "../vss" }
stratum-ewf = { path = "../ewf" }
stratum-search = { path = "../search" }
stratum-ntfs = { path = "../ntfs" }
stratum-creds = { path = "../creds" }
stratum-analysis = { path = "../analysis" }

[[bin]]
name = "partition"
path = "fuzz_targets/partition.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hive"
path = "fuzz_targets/hive.rs"
test = false
doc = false
bench = false

[[bin]]
name = "search"
path = "fuzz_targets/search.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ntfs"
path = "fuzz_targets/ntfs.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sam"
path = "fuzz_targets/sam.rs"
test = false
doc = false
bench = false

[[bin]]
name = "powershell"
path = "fuzz_targets/powershell.rs"
test = false
doc = false
bench = false

[[bin]]
name = "persistence"
path = "fuzz_targets/persistence.rs"
test = false
doc = false
bench = false

[[bin]]
name = "wof"
path = "fuzz_targets/wof.rs"
test = false
doc = false
bench = false

[[bin]]
name = "usn"
path = "fuzz_targets/usn.rs"
test = false
doc = false
bench = false

[[bin]]
name = "zone_identifier"
path = "fuzz_targets/zone_identifier.rs"
test = false
doc = false
bench = false

[[bin]]
name = "evtx"
path = "fuzz_targets/evtx.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hivelog"
path = "fuzz_targets/hivelog.rs"
test = false
doc = false
bench = false

[[bin]]
name = "shellitem"
path = "fuzz_targets/shellitem.rs"
test = false
doc = false
bench = false

[[bin]]
name = "activities"
path = "fuzz_targets/activities.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ese"
path = "fuzz_targets/ese.rs"
test = false
doc = false
bench = false

[[bin]]
name = "srum"
path = "fuzz_targets/srum.rs"
test = false
doc = false
bench = false

[[bin]]
name = "webcache"
path = "fuzz_targets/webcache.rs"
test = false
doc = false
bench = false

[[bin]]
name = "vss"
path = "fuzz_targets/vss.rs"
test = false
doc = false
bench = false

[[bin]]
name = "ewf"
path = "fuzz_targets/ewf.rs"
test = false
doc = false
bench = false

[[bin]]
name = "yara_output"
path = "fuzz_targets/yara_output.rs"
test = false
doc = false
bench = false
