[package]
name = "stratum-ewf"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Leser für Expert-Witness-Images (E01) für stratum"

[dependencies]
stratum-mmap.workspace = true
thiserror.workspace = true
miniz_oxide = "0.9.1"
adler2 = "2.0.1"

[dev-dependencies]
sha2.workspace = true
md-5 = "0.11.0"
